version: "3"

services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - postgres-pgadmin

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8585:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: fabiannosanttos@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - postgres-pgadmin

networks:
  postgres-pgadmin:

volumes:
  local_pgdata:
  pgadmin-data: